language: bash
services: docker

addons:
  apt:
    packages:
      - docker-ce

env:
  - VERSION=4.4.6 DOCKERFILE_PATH="./Dockerfile" IMAGE_NAME="manios/nagios:$VERSION"
  
# install:
#   - git clone https://github.com/manios/docker-varnish.git

before_script:
  - ./hooks/post_checkout
  - ./hooks/pre_build
  
script:
  - travis_retry ./hooks/build

after_script:
  - docker login -u manios -p "$DOCKER_PASSWORD"
  - docker push $IMAGE_NAME
  - export DOCKER_CLI_EXPERIMENTAL=enabled
  - docker manifest --help
  - ./hooks/post_push
  - docker images
  - docker manifest inspect $IMAGE_NAME
  - docker manifest create $IMAGE_NAME --amend $IMAGE_NAME-armv6
  - docker manifest annotate ${IMAGE_NAME} "${IMAGE_NAME}-armv6" --arch arm --os linux --variant v6
  - docker manifest push ${IMAGE_NAME}
  - docker logout

# vim:set et ts=2 sw=2:
