language: bash
services: docker

env:
  - VERSION=4.4.6
  - DOCKERFILE_PATH="./Dockerfile"
  - IMAGE_NAME=manios/nagios:$VERSION
  
# install:
#   - git clone https://github.com/manios/docker-varnish.git

before_script:
  - ./hooks/post_checkout
  - ./hooks/pre_build
  - git checkout v${VERSION} -b v${VERSION}
  - image="varnish:$VERSION"

script:
  - travis_retry ./hooks/pre_build

after_script:
  - ./hooks_post_push
  - docker images
  - docker inspect $IMAGE_NAME

# vim:set et ts=2 sw=2:
