sudo: true
language: bash
services: docker

addons:
  apt:
    packages:
      - docker-ce

env:
  - VERSION=4.4.6 DOCKERFILE_PATH="./Dockerfile" IMAGE_NAME="manios/nagios:$VERSION"
  
# install:
#   - git clone https://github.com/manios/docker-varnish.git

before_script:
  - ./hooks/post_checkout
  - ./hooks/pre_build
  
script:
  - travis_retry ./hooks/build

after_script:
  - docker login -u manios -p "$DOCKER_PASSWORD"
  - docker push $IMAGE_NAME
  - docker push $IMAGE_NAME-armv6
  - docker push $IMAGE_NAME-armv7
  - export DOCKER_CLI_EXPERIMENTAL=enabled
  - docker manifest --help
  - ./hooks/post_push
  - env
  - docker images
  # - docker manifest inspect $IMAGE_NAME
  # - docker manifest create $IMAGE_NAME --amend $IMAGE_NAME-armv6
  # - docker manifest annotate ${IMAGE_NAME} "${IMAGE_NAME}-armv6" --arch arm --os linux --variant v6
  # - docker manifest push ${IMAGE_NAME}
  # - ./manifest-tool push from-spec manifest-latest.yml
  - docker logout

# vim:set et ts=2 sw=2:
